{% set name = "rapidfuzz" %}
{% set version = "2.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 934b65fea75e3bd310d74903ec69ff3df061b3058ab5b7f49ab772958109bca8
  patches:
    - patches/test.patch

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - ninja
  host:
    - pip
    - python
    - numpy
    - scikit-build
    - wheel
    - setuptools
    - rapidfuzz_capi
  run:
    - jarowinkler
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - rapidfuzz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/RapidFuzz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: rapid fuzzy string matching
  dev_url: https://github.com/maxbachmann/RapidFuzz
  doc_url: https://maxbachmann.github.io/RapidFuzz/

extra:
  recipe-maintainers:
    - maxbachmann
