{% set name = "rapidfuzz" %}
{% set version = "2.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfc1d38a7adcbe8912f980a5f46f27a801dd8655582ff0d4a2c0431c02b7ce33

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - cython
    - make
  host:
    - pip
    - python
    - scikit-build
    - wheel
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - rapidfuzz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/RapidFuzz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: rapid fuzzy string matching
  dev_url: https://github.com/maxbachmann/RapidFuzz
  doc_url: https://maxbachmann.github.io/RapidFuzz/

extra:
  recipe-maintainers:
    - maxbachmann
