{% set name = "rapidfuzz" %}
{% set version = "3.14.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e13a8160d017b499ec7a2fa9d0ce1ae2e7377080815785819f966fb235d4eb60

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pip
    - python
    - scikit-build-core >=0.11
    - wheel
    - setuptools
  run:
    - python
    - numpy

test:
  imports:
    - rapidfuzz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/RapidFuzz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: rapid fuzzy string matching
  dev_url: https://github.com/maxbachmann/RapidFuzz
  doc_url: https://maxbachmann.github.io/RapidFuzz/

extra:
  recipe-maintainers:
    - xylar
    - maxbachmann
