{% set name = "rapidfuzz" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87148b96fef3b9879f7ac4e5e9aaf51641b8bae3c9d1034a2ce658a3aca13647

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vvv
  # fail to find the correct head path for Python. This will hopefully improve in scikit-build at some point
  skip: true  # [python_impl == 'pypy' and (win or (linux and (aarch64 or ppc64le)))]
  # crashes on import, since something goes wrong cross compiling
  # This should be related to https://github.com/scikit-build/scikit-build/issues/589 but I could not get a workaround working
  # at least partly because I do not have a mac for testing
  skip: true  # [osx and arm64]
  # for some completely unknown reason these crash on import in the CI.
  # It is unclear to me how segmentation faults in the conda forge build can be debugged
  skip: true  # [linux and py==37 and (aarch64 or ppc64le)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pip
    - python
    - scikit-build
    - wheel
    - setuptools
    - rapidfuzz_capi
  run:
    - jarowinkler
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - rapidfuzz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxbachmann/RapidFuzz
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: rapid fuzzy string matching
  dev_url: https://github.com/maxbachmann/RapidFuzz
  doc_url: https://maxbachmann.github.io/RapidFuzz/

extra:
  recipe-maintainers:
    - maxbachmann
